name: Mike Babb, PhD
permalink: /blog/:year/:month/:day/:title
style: kjhealy
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
#domain: mike-babb.github.io
#url: https://mike-babb.github.io 
#baseurl: /REPOSITORY-NAME/
#theme: jekyll-theme-hacker
#title: mike babb\'s about me
#description: thoughts and projects
plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'
